"""
Apply rewrite rules to a disjunct generated by read_file.py
"""
from dataclasses import is_dataclass,fields
from models import *

UNSAT = object()

def get_name(term):
    """used to extract the variable, constant, or constructor name."""
    if isinstance(term,VAR) or isinstance(term,CONSTANT):
        return term.name
    elif isinstance(term,CONSTRUCTOR_TERM):
        return term.constr
    
def substitute(obj, old_var, new_var): 
    """recursive function to substitute variables inside of any literal"""
    if isinstance(obj, VAR): # if it's a variable, directly substitute (base case)
        return new_var if obj == old_var else obj
    elif isinstance(obj, list): # recurse on each element of the list
        return [substitute(item, old_var, new_var) for item in obj]
    elif is_dataclass(obj): # if it's a dataclass, then go through each attribute, try to substitute, create new class with substitutions, move on
        new_vals = {f.name: substitute(getattr(obj, f.name), old_var, new_var) 
                    for f in fields(obj)}
        return type(obj)(**new_vals)
    elif isinstance(obj,DISJUNCT): # if it's a disjunct, just treat is as a list
        lst = substitute(obj.literals,old_var,new_var)
        new_dis = DISJUNCT(literals = lst)
        return new_dis
    return obj # anything else unexptected, just move on.

class EDiagram:
    def __init__(self):
        #dictionary that maps: var.name -> other var in the same equivalence class
        self.representatives = {}  
    
    def add_equality(self, var1: VAR, var2: VAR):
        """merge equivalence classes of var1 and var2"""
        rep1 = self.find_rep(var1)
        rep2 = self.find_rep(var2)
        if rep1.name == rep2.name:
            return
        # lexicographically smaller becomes representative
        if rep1.name < rep2.name:
            self.representatives[rep2.name] = rep1
        else:
            self.representatives[rep1.name] = rep2
    
    def find_rep(self, var: VAR) -> VAR:
        """
        find representative of var's equivalence class
        
        All vars point to some other var in the same equivalence class
        The other var must be lower in the lexicgraphical ordering,
        therefore you can never have a cycle.
        This means that eventually you must encounter a var that leads to itself.
        That var will necessarily be the lexicographically smallest var in the equivalence class,
        of which there is only one, so all vars will eventually lead to the same representative.
        """
        # if we haven't seen a var before, it is its own representative
        if var.name not in self.representatives:
            return var
        return self.find_rep(self.representatives[var.name])
    
    def to_equalities(self) -> list:
        """export as list of EQUALITY objects forming the e-diagram"""
        return [EQUALITY(lhs=VAR(name,True), rhs=self.find_rep(VAR(name)))
                for name in self.representatives]
    
    def __repr__(self)->str:
        return repr(self.to_equalities())

def rule_0(disjunct,*args):
    # Remove tautologies
    changed = False
    new_dis = DISJUNCT() # add to new list except for things we don't like
    for lit in disjunct.literals:
        if isinstance(lit,EQUALITY):
            if lit.lhs == lit.rhs:
                changed = True
                continue
        new_dis.literals.append(lit)
    if changed:
        return new_dis 
    else:
        return None
    
def rule_1(disjunct,*args):
    # A variable cannot be an atom as well as be rooted in some constructor.
    ats = set()
    heads_consts = set()
    for lit in disjunct.literals:
        if isinstance(lit,ATOMICITY):
            ats.add(lit.var.name)
        elif isinstance(lit,EQUALITY):
            if isinstance(lit.rhs,CONSTRUCTOR_TERM):
                heads_consts.add(lit.lhs.name)
    if len(ats & heads_consts) != 0:
        return UNSAT
    else:
        return None

def rule_2(disjunct,*args):
    # A variable cannot be rooted by two different constructors
    heads = dict()
    for lit in disjunct.literals:
        if isinstance(lit,EQUALITY):
            if lit.lhs.name in heads:
                heads[lit.lhs.name].append(lit.rhs)
            else:
                heads[lit.lhs.name] = [lit.rhs]

    for v,lst in heads.items():
        if len(lst) == 1:
            continue
        # only consider items in the list that are not variables
        lst = [t for t in lst if not isinstance(t,VAR)]
        # check if list items are not the same
        if any(get_name(lst[0]) != get_name(x) for x in lst[1:]):
            return UNSAT
    return None

def rule_3(disjunct,var_table,*args):
    # if a variable is the head of equality literals with the same constructor on the rhs, the arguments must be equal
    new_dis = DISJUNCT()
    changed = False
    heads = dict() # find all head of equality literals, list everything you find on the right hand side of that
    for lit in disjunct.literals:
        if isinstance(lit,EQUALITY):
            if isinstance(lit.rhs,CONSTRUCTOR_TERM):
                if lit.lhs.name in heads:
                    heads[lit.lhs.name].append(lit.rhs)
                else:
                    heads[lit.lhs.name] = [lit.rhs]
                continue
        new_dis.literals.append(lit)

    for v,lst in heads.items():
        # v is a head variable, lst is the list of terms that appear on the rhs of the literals with that head variable
        # if v is the head variable of a single equality literal, then rule doesn't apply.
        if len(lst) == 1:
            continue
        # check that all constructor terms are the same.
        # this if condition isn't necessary given that we've already had rule 2, but for redundancy's sake...
        if any(lst[0].constr != x.constr for x in lst[1:]):
            return UNSAT
        changed = True
        # we only need one equality with a constructor term
        new_dis.literals.append(EQUALITY(lhs=var_table[v],rhs=lst[0]))
        # create equality for all other variables
        for i in range(1,len(lst)):
            for lvar,rvar in zip(lst[0].var_list,lst[i].var_list):
                new_dis.literals.append(EQUALITY(lhs=lvar,rhs=rvar))
    if changed:
        return new_dis
    else:
        return None

def rule_4(disjunct, var_table, ediagram, *args):
    # remove equality literals that only have free variables and add them to the e-diagram
    new_dis = DISJUNCT()
    changed = False
    # find equality literals we want to remove, the rest we add to our new disjunction
    for lit in disjunct.literals:
        if isinstance(lit, EQUALITY):
            if isinstance(lit.lhs, VAR) and isinstance(lit.rhs, VAR):
                if lit.lhs.is_free and lit.rhs.is_free:
                    changed = True
                    ediagram.add_equality(lit.lhs, lit.rhs)
                    continue
        new_dis.literals.append(lit)
    if changed:
        # for each variable that appears in the e-diagram, 
        # substitute it in the disjunct with the representative of its equivalence class
        for name, var in ediagram.representatives.items():
            repres = ediagram.find_rep(var)
            new_dis = substitute(new_dis, var_table[name], repres)
        return new_dis
    else:
        return None

def rule_5(disjunct,*args):
    new_dis = DISJUNCT()
    changed = False
    substitutions = []
    for lit in disjunct.literals:
        if isinstance(lit,EQUALITY):
            if not lit.lhs.is_free and isinstance(lit.rhs,VAR):
                substitutions.append(lit)
                changed = True
                continue
        new_dis.literals.append(lit)
    if changed:
        for lit in substitutions:    
            new_dis = substitute(new_dis,lit.lhs,lit.rhs)
        return new_dis
    else:
        return None

def rule_6(disjunct,*args):
    # check for direct contradictions.
    # this one isn't written in the thesis, but should be self-evident
    for lit in disjunct.literals:
        if isinstance(lit,INEQUALITY):
            if lit.lhs == lit.rhs:
                return UNSAT
    return None


def apply_rewrite_rules(all_disjuncts: list[DISJUNCT],var_table):
    new_disjuncts = []
    Ediagrams = []
    null_disjunct_flag = False
    step = 0
    for disjunct in all_disjuncts:
        # print("---DISJUNCT:",step)
        step+=1
        outside_scope = EDiagram() # store equalities that will form an e-diagram.
        changed = True
        # apply rules
        while changed:
            changed = False
            for i,rule in enumerate([rule_0,rule_1,rule_2,rule_3,rule_4,rule_5,rule_6]):
                # print('rule',i)
                result = rule(disjunct,var_table,outside_scope)
                if result is UNSAT: # contradiction found
                    # print('UNSAT')
                    null_disjunct_flag = True
                    break
                elif result is not None:
                    # print('change is true')
                    disjunct = result
                    changed = True
                    break # start over
            if null_disjunct_flag:
                break
        if not null_disjunct_flag:
            assert isinstance(disjunct,DISJUNCT) # typing shenanigans
            if disjunct.literals: # check that the disjunct is not empty
                new_disjuncts.append(disjunct)
                Ediagrams.append(outside_scope)
        else:
            null_disjunct_flag = False
    return new_disjuncts,Ediagrams


if __name__ == '__main__':

    from file_reader import parse_file
    disjuncts, var_table, constructor_table = parse_file("rewrite_tests.txt")
    new_dis,Ediagrams = apply_rewrite_rules(disjuncts,var_table)
    for i,dis in enumerate(new_dis):
        print("\n---DISJUNCT",i)
        print(dis)
        print("-E diagram")
        print(Ediagrams[i])